package com.shitulelv.aicollab.common.exception;

import org.springframework.http.HttpStatus;

/**
 * 集中定义客户端可依赖的业务错误码、默认提示与 HTTP 语义。
 * 它连接业务异常和 HTTP 层，避免各处自行选择状态码造成契约不一致。
 */
public enum ErrorCode {
    SUCCESS(HttpStatus.OK, "操作成功"),
    VALIDATION_ERROR(HttpStatus.BAD_REQUEST, "请求参数校验失败"),
    AUTH_INVALID_CREDENTIALS(HttpStatus.UNAUTHORIZED, "用户名或密码错误"),
    AUTH_UNAUTHORIZED(HttpStatus.UNAUTHORIZED, "当前登录状态无效，请重新登录"),
    AUTH_FORBIDDEN(HttpStatus.FORBIDDEN, "没有权限执行此操作"),
    USER_DISABLED(HttpStatus.FORBIDDEN, "账号已被禁用"),
    USER_NOT_FOUND(HttpStatus.NOT_FOUND, "用户不存在"),
    REGISTRATION_DISABLED(HttpStatus.FORBIDDEN, "当前未开放公开注册"),
    USERNAME_ALREADY_EXISTS(HttpStatus.CONFLICT, "用户名已存在"),
    EMAIL_ALREADY_EXISTS(HttpStatus.CONFLICT, "邮箱已存在"),
    CURRENT_PASSWORD_INVALID(HttpStatus.BAD_REQUEST, "当前密码不正确"),
    NEW_PASSWORD_SAME_AS_CURRENT(HttpStatus.BAD_REQUEST, "新密码不能与当前密码相同"),
    PROJECT_NOT_FOUND(HttpStatus.NOT_FOUND, "项目不存在"),
    PROJECT_READ_ONLY(HttpStatus.CONFLICT, "当前项目状态为只读，不能修改项目文档"),
    PROJECT_DOCUMENTS_EXIST(HttpStatus.CONFLICT, "项目中仍有文档，请先删除全部文档后再删除项目"),
    PROJECT_CONFIRMED_PLANS_EXIST(HttpStatus.CONFLICT, "项目中仍有已确认的AI规划，无法删除"),
    PROJECT_ADMIN_REQUIRED(HttpStatus.FORBIDDEN, "需要项目管理员权限"),
    PROJECT_OWNER_REQUIRED(HttpStatus.FORBIDDEN, "需要项目所有者权限"),
    PROJECT_OWNER_CANNOT_BE_REMOVED(HttpStatus.FORBIDDEN, "项目所有者不能被降级或移除"),
    PROJECT_OWNER_CANNOT_LEAVE(HttpStatus.FORBIDDEN, "项目所有者不能退出项目，请先转移所有权"),
    PROJECT_OWNERSHIP_SELF_TRANSFER(HttpStatus.BAD_REQUEST, "不能将项目所有权转移给自己"),
    PROJECT_OWNERSHIP_TARGET_NOT_MEMBER(HttpStatus.NOT_FOUND, "目标成员已不在项目中"),
    PROJECT_OWNERSHIP_CONFLICT(HttpStatus.CONFLICT, "项目所有权已发生变化，请刷新后重试"),
    MEMBER_ALREADY_EXISTS(HttpStatus.CONFLICT, "用户已经是项目成员"),
    MEMBER_NOT_FOUND(HttpStatus.NOT_FOUND, "项目成员不存在"),
    INVITATION_INVALID(HttpStatus.GONE, "邀请无效"),
    INVITATION_EXPIRED(HttpStatus.GONE, "邀请已过期"),
    INVITATION_ALREADY_USED(HttpStatus.GONE, "邀请已被使用"),
    INVITATION_EMAIL_MISMATCH(HttpStatus.FORBIDDEN, "当前账号与邀请邮箱不匹配"),
    MILESTONE_NOT_FOUND(HttpStatus.NOT_FOUND, "里程碑不存在"),
    TASK_NOT_FOUND(HttpStatus.NOT_FOUND, "任务不存在"),
    TASK_ASSIGNEE_NOT_MEMBER(HttpStatus.BAD_REQUEST, "负责人不是当前项目成员"),
    TASK_MILESTONE_CROSS_PROJECT(HttpStatus.BAD_REQUEST, "里程碑不属于当前项目"),
    TASK_INVALID_STATUS_TRANSITION(HttpStatus.CONFLICT, "不允许的任务状态转换"),
    TASK_BLOCKED_BY_DEPENDENCY(HttpStatus.CONFLICT, "任务仍有未完成依赖"),
    TASK_DEPENDENCY_CYCLE(HttpStatus.CONFLICT, "任务依赖不能形成环"),
    TASK_DEPENDENCY_CROSS_PROJECT(HttpStatus.BAD_REQUEST, "依赖任务不属于当前项目"),
    COMMENT_NOT_FOUND(HttpStatus.NOT_FOUND, "评论不存在"),
    COMMENT_AUTHOR_REQUIRED(HttpStatus.FORBIDDEN, "只有评论作者可以修改评论"),
    DOCUMENT_NOT_FOUND(HttpStatus.NOT_FOUND, "文档不存在或无权访问"),
    DOCUMENT_UNSUPPORTED_TYPE(HttpStatus.UNSUPPORTED_MEDIA_TYPE, "暂不支持该文件类型"),
    DOCUMENT_TOO_LARGE(HttpStatus.CONTENT_TOO_LARGE, "文件大小不能超过 20MB"),
    DOCUMENT_LIMIT_EXCEEDED(HttpStatus.CONFLICT, "当前项目文档数量已达上限"),
    DOCUMENT_EMPTY(HttpStatus.BAD_REQUEST, "不能上传空文件"),
    DOCUMENT_INVALID_FILE(HttpStatus.BAD_REQUEST, "文件内容与文件类型不匹配"),
    DOCUMENT_NOT_READY(HttpStatus.CONFLICT, "文档尚未完成处理"),
    DOCUMENT_PROCESSING_CONFLICT(HttpStatus.CONFLICT, "文档当前状态不允许执行该操作"),
    DOCUMENT_PARSE_FAILED(HttpStatus.UNPROCESSABLE_CONTENT, "文档解析失败"),
    DOCUMENT_EMBEDDING_FAILED(HttpStatus.BAD_GATEWAY, "文档向量化失败，请检查模型配置后重试"),
    DOCUMENT_STORAGE_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE, "文件存储服务暂时不可用"),
    KNOWLEDGE_SESSION_NOT_FOUND(HttpStatus.NOT_FOUND, "问答会话不存在"),
    AI_RATE_LIMIT_EXCEEDED(HttpStatus.TOO_MANY_REQUESTS, "问答请求过于频繁，请稍后再试"),
    AI_PROVIDER_QUOTA_EXCEEDED(HttpStatus.TOO_MANY_REQUESTS, "模型服务额度不足，请稍后再试"),
    AI_PROVIDER_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE, "模型服务尚未配置或暂时不可用"),
    AI_MODEL_CREDENTIAL_INVALID(HttpStatus.SERVICE_UNAVAILABLE, "模型凭据无法解密，请在系统管理中重新填写 API Key"),
    AI_MODEL_TIMEOUT(HttpStatus.GATEWAY_TIMEOUT, "模型服务响应超时"),
    AI_PROVIDER_ERROR(HttpStatus.BAD_GATEWAY, "模型服务调用失败"),
    AI_PROVIDER_INVALID_RESPONSE(HttpStatus.BAD_GATEWAY, "模型服务返回了无效响应"),
    AI_PROVIDER_OUTPUT_TRUNCATED(HttpStatus.BAD_GATEWAY, "模型输出被截断"),
    TASK_PLAN_NOT_FOUND(HttpStatus.NOT_FOUND, "任务规划不存在"),
    TASK_PLAN_STATE_CONFLICT(HttpStatus.CONFLICT, "任务规划当前状态不允许此操作"),
    TASK_PLAN_VERSION_NOT_FOUND(HttpStatus.NOT_FOUND, "任务规划版本不存在"),
    PLAN_VERSION_CONFLICT(HttpStatus.CONFLICT, "规划版本已更新，请加载最新版本"),
    PLAN_REPAIR_ISSUE_INVALID(HttpStatus.BAD_REQUEST, "局部修复问题不存在或不属于当前规划"),
    PLAN_REPAIR_ISSUE_CONFLICT(HttpStatus.CONFLICT, "局部修复问题已过期或已解决，请加载最新版本"),
    PLAN_VALIDATION_FAILED(HttpStatus.UNPROCESSABLE_CONTENT, "规划草案未通过领域校验"),
    PLAN_GENERATION_FAILED(HttpStatus.UNPROCESSABLE_CONTENT, "规划骨架生成失败"),
    PLAN_DETAIL_GENERATION_FAILED(HttpStatus.UNPROCESSABLE_CONTENT, "规划细节生成失败"),
    PLAN_GENERATION_CANCELED(HttpStatus.CONFLICT, "规划生成已取消"),
    PLAN_ALREADY_CONFIRMED(HttpStatus.CONFLICT, "规划已经确认"),
    IDEMPOTENCY_KEY_REUSED(HttpStatus.CONFLICT, "幂等键已用于不同请求"),
    PLANNING_MODEL_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE, "规划模型尚未配置或暂时不可用"),
    PLANNING_MODEL_TIMEOUT(HttpStatus.GATEWAY_TIMEOUT, "规划模型响应超时，可稍后重试"),
    PLANNING_MODEL_RATE_LIMITED(HttpStatus.TOO_MANY_REQUESTS, "规划模型请求受限"),
    PLANNING_MODEL_INVALID_OUTPUT(HttpStatus.UNPROCESSABLE_CONTENT, "模型未能生成有效规划，可重新生成或重试细节"),
    PLANNING_GENERATION_QUOTA_EXCEEDED(HttpStatus.TOO_MANY_REQUESTS, "过去 60 分钟成功生成的 AI 规划次数已达上限"),
    PLANNING_ATTEMPT_RATE_LIMITED(HttpStatus.TOO_MANY_REQUESTS, "操作过于频繁，请稍后再试"),
    PLANNING_MODEL_OUTPUT_TRUNCATED(HttpStatus.UNPROCESSABLE_CONTENT, "模型输出过长被截断，请减少最大任务数或重新生成"),
    PLANNING_PROVIDER_QUOTA_EXCEEDED(HttpStatus.TOO_MANY_REQUESTS, "规划模型服务额度不足，请检查供应商账户或稍后再试"),
    PLANNING_DOCUMENT_NOT_READY(HttpStatus.CONFLICT, "所选规划文档尚未就绪"),
    PLANNING_DOCUMENT_LIMIT_EXCEEDED(HttpStatus.BAD_REQUEST, "规划最多选择 10 个文档"),
    PLANNING_QUEUE_FULL(HttpStatus.SERVICE_UNAVAILABLE, "规划生成队列已满"),
    TASK_PLAN_HAS_BLOCKING_ISSUES(HttpStatus.CONFLICT, "规划仍有需要处理的问题，解决后才能创建正式任务"),
    VERSION_CONFLICT(HttpStatus.CONFLICT, "数据已被其他请求修改，请刷新后重试"),
    ADMIN_REQUIRED(HttpStatus.FORBIDDEN, "需要系统管理员权限"),
    USER_ALREADY_DISABLED(HttpStatus.CONFLICT, "用户已被禁用"),
    USER_ALREADY_ACTIVE(HttpStatus.CONFLICT, "用户已是正常状态"),
    CANNOT_DISABLE_SELF(HttpStatus.FORBIDDEN, "不能禁用自己的账号"),
    CANNOT_DISABLE_SUPER_ADMIN(HttpStatus.FORBIDDEN, "不能禁用超级管理员"),
    NOTIFICATION_NOT_FOUND(HttpStatus.NOT_FOUND, "通知不存在"),
    AGENT_SESSION_NOT_FOUND(HttpStatus.NOT_FOUND, "Agent 会话不存在"),
    AGENT_RUN_NOT_FOUND(HttpStatus.NOT_FOUND, "Agent 运行不存在"),
    AGENT_APPROVAL_NOT_FOUND(HttpStatus.NOT_FOUND, "Agent 审批不存在"),
    AGENT_APPROVAL_EXPIRED(HttpStatus.GONE, "Agent 审批已过期"),
    AGENT_APPROVAL_CONFLICT(HttpStatus.CONFLICT, "Agent 审批已处理或发生冲突"),
    AGENT_APPROVAL_NONCE_INVALID(HttpStatus.FORBIDDEN, "Agent 审批凭证无效"),
    AGENT_APPROVAL_REVALIDATION_FAILED(HttpStatus.CONFLICT, "Agent 审批执行前重校验失败"),
    AGENT_APPROVAL_RESOURCE_GONE(HttpStatus.GONE, "Agent 审批目标实体已不存在"),
    AGENT_APPROVAL_VERSION_CONFLICT(HttpStatus.CONFLICT, "Agent 审批目标实体版本已变更"),
    AGENT_SCHEDULE_NOT_FOUND(HttpStatus.NOT_FOUND, "Agent 定时任务不存在"),
    AGENT_SKILL_NOT_FOUND(HttpStatus.NOT_FOUND, "Agent Skill 不存在"),
    AGENT_SKILL_NOT_ALLOWED(HttpStatus.FORBIDDEN, "当前 Skill 不允许此操作"),
    AGENT_RUN_CANCELED(HttpStatus.CONFLICT, "Agent 运行已取消"),
    AGENT_RUN_NOT_CANCELABLE(HttpStatus.CONFLICT, "Agent 运行当前不可取消"),
    AGENT_EVENT_CURSOR_INVALID(HttpStatus.BAD_REQUEST, "Agent 事件游标无效"),
    AGENT_CONTEXT_RESOURCE_INVALID(HttpStatus.BAD_REQUEST, "页面上下文资源无效"),
    AGENT_TOOL_NOT_FOUND(HttpStatus.NOT_FOUND, "Agent 工具不存在"),
    AGENT_TOOL_NOT_ALLOWED(HttpStatus.FORBIDDEN, "当前 Skill 不允许使用此工具"),
    AGENT_TOOL_RESULT_TOO_LARGE(HttpStatus.PAYLOAD_TOO_LARGE, "工具结果过大"),
    AGENT_MCP_CONNECTION_NOT_FOUND(HttpStatus.NOT_FOUND, "MCP 连接不存在"),
    AGENT_MCP_CONNECTION_DISABLED(HttpStatus.CONFLICT, "MCP 连接已停用"),
    AGENT_MCP_TIMEOUT(HttpStatus.GATEWAY_TIMEOUT, "MCP 连接响应超时"),
    AGENT_MCP_SCHEMA_CHANGED(HttpStatus.CONFLICT, "MCP 工具定义已变化，请管理员确认"),
    AGENT_MCP_ENDPOINT_FORBIDDEN(HttpStatus.BAD_REQUEST, "MCP 接口地址不在安全允许范围"),
    AGENT_MCP_DATA_INVALID(HttpStatus.INTERNAL_SERVER_ERROR, "MCP 连接数据格式无效"),
    AGENT_MEMORY_NOT_FOUND(HttpStatus.NOT_FOUND, "Agent 项目记忆不存在"),
    AGENT_NO_PROGRESS(HttpStatus.CONFLICT, "Agent 无进展循环"),
    TOOL_ARGUMENT_INVALID(HttpStatus.BAD_REQUEST, "工具参数校验失败"),
    TOOL_EXECUTION_TIMEOUT(HttpStatus.GATEWAY_TIMEOUT, "工具执行超时"),
    INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "系统内部错误");

    private final HttpStatus httpStatus;
    private final String message;

    ErrorCode(HttpStatus httpStatus, String message) {
        this.httpStatus = httpStatus;
        this.message = message;
    }

    public HttpStatus httpStatus() {
        return httpStatus;
    }

    public String message() {
        return message;
    }
}
