-- 添加 WAITING_FOR_USER_INPUT 到 agent_run_event 表的 type 约束
-- 这是 V35 遗漏的修复，确保多轮对话功能正常工作

ALTER TABLE agent_run_event DROP CONSTRAINT ck_agent_run_event_type;
ALTER TABLE agent_run_event ADD CONSTRAINT ck_agent_run_event_type CHECK (type IN (
    'RUN_CREATED','CONTEXT_CAPTURED','SKILL_SELECTED',
    'PLAN_CREATED','PLAN_UPDATED','MODEL_STARTED','MODEL_COMPLETED',
    'TOOL_CALL_PROPOSED','TOOL_CALL_STARTED','TOOL_CALL_COMPLETED','TOOL_CALL_FAILED',
    'APPROVAL_REQUESTED','APPROVAL_APPROVED','APPROVAL_REJECTED',
    'APPROVAL_EXPIRED','RESULT_VERIFIED','RUN_RETRY_SCHEDULED',
    'RUN_CANCELED','RUN_SUCCEEDED','RUN_FAILED','RUN_BUDGET_EXCEEDED',
    'WAITING_FOR_USER_INPUT'
));