package com.shitulelv.aicollab.agent.domain.model;

public enum AgentEventType {
    RUN_CREATED,
    CONTEXT_CAPTURED,
    SKILL_SELECTED,
    PLAN_CREATED,
    PLAN_UPDATED,
    MODEL_STARTED,
    MODEL_COMPLETED,
    TOOL_CALL_PROPOSED,
    TOOL_CALL_STARTED,
    TOOL_CALL_COMPLETED,
    TOOL_CALL_FAILED,
    APPROVAL_REQUESTED,
    APPROVAL_APPROVED,
    APPROVAL_REJECTED,
    APPROVAL_EXPIRED,
    RESULT_VERIFIED,
    RUN_RETRY_SCHEDULED,
    RUN_CANCELED,
    RUN_SUCCEEDED,
    RUN_FAILED,
    RUN_BUDGET_EXCEEDED
}
